# Generated by Django 4.2.6 on 2023-11-17 10:16

import apps.children.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('middlename', models.CharField(db_index=True, max_length=100, verbose_name='Middlename')),
                ('surname', models.CharField(db_index=True, max_length=100, verbose_name='Surname')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.children.models.profile_avatar_path)),
                ('bio', models.TextField(blank=True, db_index=True, verbose_name='Bio')),
            ],
            options={
                'verbose_name': 'child',
                'verbose_name_plural': 'children',
            },
        ),
    ]
