# Generated by Django 4.2.6 on 2023-11-19 11:21

import apps.children.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_child_addition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], default='M', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='child',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.children.models.profile_avatar_path, verbose_name='Photo'),
        ),
    ]
