# Generated by Django 4.2.6 on 2023-11-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_child_gender_alter_child_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='Archived'),
        ),
    ]
