# Generated by Django 4.2.6 on 2023-11-09 14:20

import apps.userprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='undraw_profile.svg', null=True, upload_to=apps.userprofile.models.profile_avatar_path),
        ),
    ]
